name: 'Sources and Citations'
id: 8
description: |
  How do you find good sources, and cite them on Wikipedia? This tutorial will show you how.
estimated_ttc: 10 minutes
slides:
  - slug: citations-review # 801
  - slug: why-verify # 802
  - slug: examples-of-reliable-sources # 803
  - slug: gather-your-sources # 804
  - slug: add-a-citation-refresher # 805
  - slug: sources-and-citations-complete # 806
