#!/usr/bin/env bash
# MIT © Minh Duc Vo <minhducsun2002@gmail.com>

SCRIPT_PATH=$(dirname $0)
SCRIPT_ABSOLUTE_PATH=$(realpath -s $SCRIPT_PATH)

YELLOW='\033[1;33m'
NC='\033[0m' # No Color


printf "This will overwrite your current post-merge hook with ${YELLOW}$SCRIPT_ABSOLUTE_PATH/hooks/pull-update-deps${NC}.\n"
cp -i "$SCRIPT_PATH/hooks/pull-update-deps" "$SCRIPT_ABSOLUTE_PATH/../.git/hooks/post-merge"
