version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: faraday
    versions:
    - 1.3.0
    - 1.4.0
  - dependency-name: newrelic_rpm
    versions:
    - 6.15.0
  - dependency-name: chartkick
    versions:
    - 4.0.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-dnd
    versions:
    - "< 5, >= 4.a"
  - dependency-name: react-dnd
    versions:
    - "< 6, >= 5.a"
  - dependency-name: react-dnd
    versions:
    - ">= 6.a, < 7"
  - dependency-name: react-dnd
    versions:
    - ">= 7.a, < 8"
  - dependency-name: react-dnd-html5-backend
    versions:
    - ">= 7.a, < 8"
  - dependency-name: react-dnd-touch-backend
    versions:
    - "< 1, > 0.3.15"
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: react-dnd
    versions:
    - 11.1.3
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-dnd-touch-backend
    versions:
    - 11.1.3
    - 12.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: react-redux
    versions:
    - 7.2.2
