engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true

ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.jsx"
  - "**.css"
  - Gemfile.lock

# For all languages, we support a standard set of Glob patterns.
# exclude_paths:
# - app/helpers/users_helper.php # Exclude a specific file
# - app/controllers/* # Exclude all contents of a folder (including all subfolders)
# - app/controllers/*.py # Exclude specific files type within a folder/subfolders
# - lib/**/*.rb # Recursively ignore all files ending in .rb

exclude_paths:
- public/*
- db/*
- fixtures/*
- vendor/*
- spec/*
- docs/*
