Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'db/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'app/views/**/**/*.haml'
    - 'docs/**/*'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

###################
# Spec exceptions #
###################
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*' # RSpec comparison matchers don't have predicate versions
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*' # pretty much impossible with RSpec
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*' # not a big deal in spec helper methods
# Disable complexity cops, since we use CodeClimate for that.
# Metrics/MethodLength:
#   Enabled: false
# Metrics/AbcSize:
#   Enabled: false
# Metrics/ClassLength:
#   Enabled: false
# Metrics/CyclomaticComplexity:
#   Enabled: false
# Metrics/PerceivedComplexity:
#   Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/NumericLiterals:
  # We should use underscores when the number is meaningful. But when it's
  # an arbitrary number like a user id, underscores are just clutter.
  Enabled: false
Style/AsciiComments:
  Enabled: false # We need non-ascii characters to document Wikipedia stuff.
Style/ParallelAssignment:
  Enabled: false # We generally use this only to initialize empty variables.
Style/RedundantReturn:
  Enabled: false # Sometimes a redundant return enhances clarity.
Naming/VariableNumber:
  Enabled: false # Not very helpful, and conflicts with wp10-related names
