require:
  - rubocop/rspec/focused

Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'db/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'app/views/**/**/*.haml'
    - 'docs/**/*'
    - 'setup/*'
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 140 # We should bring this down, ideally to the default of 100
  Exclude: # These are too big, and should be shrunk if feasible.
    - 'lib/importers/category_importer.rb'
    - 'app/models/course.rb'
    - 'app/controllers/surveys_controller.rb'
    - 'app/controllers/campaigns_controller.rb'
    - 'app/controllers/courses_controller.rb'
    - 'lib/analytics/histogram_plotter.rb'

Metrics/AbcSize:
  Max: 44 # We should bring this down, ideally to the default of 15
  Exclude:
    - 'spec/**/*' # not a big deal in spec helper methods

Style/NumericPredicate:
  Exclude:
    - 'spec/**/*' # RSpec comparison matchers don't have predicate versions
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*' # pretty much impossible with RSpec
    - 'lib/tasks/*' # also impractical for Rake tasks
    - 'app/views/**/*' # jbuilder requires long blocks for large json views
Metrics/MethodLength:
  Max: 16 # We should bring this down, ideally to the default of 10
  Exclude:
    - 'spec/**/*' # not a big deal in spec helper methods
Metrics/ModuleLength:
  Max: 145 # We should bring this down, ideally to the default of 100
  Exclude:
    - 'spec/**/*' # not a big deal in spec helper module
    - 'app/helpers/surveys_helper.rb'

########################
# Permanent exceptions #
########################

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/NumericLiterals:
  # We should use underscores when the number is meaningful. But when it's
  # an arbitrary number like a user id, underscores are just clutter.
  Enabled: false
Style/AsciiComments:
  Enabled: false # We need non-ascii characters to document Wikipedia stuff.
Style/ParallelAssignment:
  Enabled: false # We generally use this only to initialize empty variables.
Style/RedundantReturn:
  Enabled: false # Sometimes a redundant return enhances clarity.
Style/SymbolArray:
  Enabled: false # Rare syntax that is potentially confusing to newcomers.
Naming/VariableNumber:
  Enabled: false # Not very helpful, and conflicts with wp10-related names
Rails/Blank:
  Enabled: false # Sometimes unless foo.present? is more expressive.
Layout/EmptyLineAfterMagicComment:
  Enabled: false # These get removed whenever 'annotate' updates a file anyway.
Naming/UncommunicativeMethodParamName:
  Enabled: false # This is too restrictive. Calling errors `e` is fine, for example.
########################
# Temporary exceptions #
########################

# These should be enabled once violations are fixed,
# or they should be moved to the 'Permanent' section
# if we decide they shouldn't be fixed.

Style/FormatStringToken:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Rails/Date:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Performance/UnfreezeString:
  Enabled: false
Style/GuardClause:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/UnknownEnv:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Performance/RegexpMatch:
  Enabled: false
Rails/Delegate:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/Validation:
  Enabled: false
Rails/FindBy:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
Rails/Output:
  Enabled: false
Lint/DuplicateMethods:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Rails/ActiveRecordAliases:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
