Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 100

# Disable complexity cops, since we use CodeClimate for that.
# Metrics/MethodLength:
#   Enabled: false
# Metrics/AbcSize:
#   Enabled: false
# Metrics/ClassLength:
#   Enabled: false
# Metrics/CyclomaticComplexity:
#   Enabled: false
# Metrics/PerceivedComplexity:
#   Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/NumericLiterals:
  # We should use underscores when the number is meaningful. But when it's
  # an arbitrary number like a user id, underscores are just clutter.
  Enabled: false
Style/AsciiComments:
  Enabled: false # We need non-ascii characters to document Wikipedia stuff.
Style/ParallelAssignment:
  Enabled: false # We generally use this only to initialize empty variables.
Style/RedundantReturn:
  Enabled: false # Sometimes a redundant return enhances clarity.
