id: 342
title: The application process
summary:
content: |
  You must apply each term to be considered for a spot in Wiki Education's Wikipedia Student
  Program. To complete your application, go through this orientation and then submit a course
  page on the Dashboard. You'll be prompted to create your course page at the end of this
  orientation.
