# Used by sidekiq-cron
# Loaded in the sidekiq initializer
# For usage see https://github.com/ondrejbartas/sidekiq-cron

# Course updates will pull in revisions and articles for courses that are ongoing
# or still within the update window. They are sorted into queues depending on how
# long they run, with short courses having their own queue and very long ones their
# own as well.
schedule_course_updates:
  cron: "*/5 * * * *" # execute at every 5 minutes
  class: "ScheduleCourseUpdatesWorker"
  queue: default # Schedule course updates is a quick process, and default queue is usually empty.

# Constant updates are independent of the main course stats, pulling in revision
# metadata, generating alerts, and doing other data and network-intensive tasks,
# for all current courses.
update_constantly:
  cron: "*/4 * * * *" # execute at every 4 minutes
  class: "ConstantUpdateWorker"
  queue: constant_update

# This pulls in additional data and performs other tasks that do not need to be
# done many times per day.
update_daily:
  cron: "30 11 * * *"
  class: "DailyUpdateWorker"
  queue: daily_update

# Assigns surveys to users who are newly eligible and sends
# survey notification and reminder emails
survey_emails:
  cron: "15 17 * * 1,2,3,4" # every Monday, Tuesday, Wednesday, Thursday at 10:15am PT (UTC -7)
  class: "SurveyUpdateWorker"
  queue: constant_update

# Emails admins to let them know when they have open support tickets
open_ticket_emails:
  cron: "0 13,20 * * 1,2,3,4,5" # every weekday at 6am and 1pm PT (UTC -7)
  class: "TicketNotificationsWorker"
  queue: constant_update

# Update default campaign at the beginning of spring and fall semesters (based on academic calendar - northern hemisphere)
update_default_campaign:
  cron: "1 0 1 1,7 *" # every January, 1st and July, 1st at 00:01 (UTC -7)
  class: "DefaultCampaignUpdateWorker"
  queue: default
