name: 'Sources and Citations'
id: 8
description: |
  How do you find good sources, and cite them on Wikipedia? This tutorial will show you how.
slides:
  - slug: citations-review # 801
  - slug: why-verify # 802
  - slug: wikicode-citations-review # 803
  - slug: cite-gadget-review # 804
  - slug: visualeditor-citations # 717
  - slug: citations-video # 718
  - slug: sources-and-citations-complete # 805
